apiVersion: v1
data:
  students.yaml: |-
    app:
      name: students
    http:
      mode: release
      port: 8080
    db:
      url: root:{{ .Values.mysql.mysqlRootPassword }}@tcp({{ .Values.mysql.mysqlHost }}:3306)/{{ .Values.mysql.mysqlDatabase }}?charset=utf8&parseTime=True&loc=Local
      debug : false
    log:
      filename: /tmp/students.log
      maxSize: 500
      maxBackups: 3
      maxAge: 3
      level: "debug"
      stdout: true
kind: ConfigMap
metadata:
  name: {{ include "student.fullname" . }}-cm
